#import <Foundation/Foundation.h>
#import <sys/socket.h>
#import <sys/un.h>
#import <unistd.h>
#import <libproc.h>
#import <signal.h>
#import "BrowserIdentity.h"
static BOOL transfer(int fd,void *p,size_t n,BOOL writing){while(n){ssize_t k=writing?write(fd,p,n):read(fd,p,n);if(k<=0)return NO;p+=k;n-=k;}return YES;}
static NSDictionary *request(NSDictionary *m){int fd=socket(AF_UNIX,SOCK_STREAM,0);struct sockaddr_un a={.sun_family=AF_UNIX};NSString *path=[NSHomeDirectory() stringByAppendingPathComponent:@"Library/Application Support/Less Pull/browser.sock"];strlcpy(a.sun_path,path.fileSystemRepresentation,sizeof(a.sun_path));struct timeval t={.tv_sec=4};setsockopt(fd,SOL_SOCKET,SO_RCVTIMEO,&t,sizeof(t));setsockopt(fd,SOL_SOCKET,SO_SNDTIMEO,&t,sizeof(t));if(connect(fd,(void *)&a,sizeof(a))){close(fd);return @{@"ok":@NO,@"error":@"Open Less Pull on this Mac, then try again."};}NSData *data=[NSJSONSerialization dataWithJSONObject:m options:0 error:nil];uint32_t size=(uint32_t)data.length;NSDictionary *out=nil;if(transfer(fd,&size,4,YES)&&transfer(fd,(void *)data.bytes,size,YES)&&transfer(fd,&size,4,NO)&&size<=65536){NSMutableData *r=[NSMutableData dataWithLength:size];if(transfer(fd,r.mutableBytes,size,NO))out=[NSJSONSerialization JSONObjectWithData:r options:0 error:nil];}close(fd);return out?:@{@"ok":@NO,@"error":@"Less Pull did not respond. Reopen the app."};}
static NSString *browserParent(){pid_t pid=getppid();for(int i=0;i<8&&pid>1;i++){char path[PROC_PIDPATHINFO_MAXSIZE]={0};proc_pidpath(pid,path,sizeof(path));NSString *p=@(path);if([p containsString:@"Brave Browser.app/"])return @"com.brave.Browser";if([p containsString:@"Google Chrome.app/"])return @"com.google.Chrome";if([p containsString:@"Firefox.app/"]||[p containsString:@"Firefox Developer Edition.app/"]||[p containsString:@"Firefox Nightly.app/"])return @"org.mozilla.firefox";if([p containsString:@"Opera.app/"]||[p containsString:@"Opera GX.app/"])return @"com.operasoftware.Opera";if([p containsString:@"Microsoft Edge.app/"])return @"com.microsoft.edgemac";struct proc_bsdinfo info={0};if(proc_pidinfo(pid,PROC_PIDTBSDINFO,0,&info,sizeof(info))!=sizeof(info))break;pid=info.pbi_ppid;}return nil;}
int main(int argc,char **argv){@autoreleasepool{signal(SIGPIPE,SIG_IGN);
 if(argc==2&&strcmp(argv[1],"--install")==0){NSString *executable=[NSString stringWithUTF8String:argv[0]];if(!executable.isAbsolutePath)executable=[NSFileManager.defaultManager.currentDirectoryPath stringByAppendingPathComponent:executable];executable=executable.stringByStandardizingPath;NSDictionary *manifest=@{@"name":@"local.less_pull.browser",@"description":@"Less Pull local website bridge",@"path":executable,@"type":@"stdio",@"allowed_origins":LESS_PULL_EXTENSION_ORIGINS};NSData *d=[NSJSONSerialization dataWithJSONObject:manifest options:NSJSONWritingPrettyPrinted error:nil];// Firefox uses allowed_extensions (the add-on id) instead of allowed_origins.
 NSDictionary *firefoxManifest=@{@"name":@"local.less_pull.browser",@"description":@"Less Pull local website bridge",@"path":executable,@"type":@"stdio",@"allowed_extensions":@[@LESS_PULL_FIREFOX_ID]};NSData *df=[NSJSONSerialization dataWithJSONObject:firefoxManifest options:NSJSONWritingPrettyPrinted error:nil];
 for(NSArray *target in @[@[@"Google/Chrome",d],@[@"BraveSoftware/Brave-Browser",d],@[@"Mozilla",df],@[@"com.operasoftware.Opera",d],@[@"Microsoft Edge",d]]){NSString *dir=[NSHomeDirectory() stringByAppendingPathComponent:[NSString stringWithFormat:@"Library/Application Support/%@/NativeMessagingHosts",target[0]]];NSError *e=nil;if(![NSFileManager.defaultManager createDirectoryAtPath:dir withIntermediateDirectories:YES attributes:nil error:&e]||![target[1] writeToFile:[dir stringByAppendingPathComponent:@"local.less_pull.browser.json"] options:NSDataWritingAtomic error:&e]){fprintf(stderr,"Bridge installation failed: %s\n",e.localizedDescription.UTF8String);return 1;}}puts("Less Pull bridge installed for Chrome, Brave, Firefox, Opera and Edge.");return 0;}
 // Chromium passes the extension origin; Firefox passes the manifest path and the add-on id.
 BOOL chromium=argc>=2&&[LESS_PULL_EXTENSION_ORIGINS containsObject:@(argv[1])],firefox=argc>=3&&strcmp(argv[2],LESS_PULL_FIREFOX_ID)==0;if(!chromium&&!firefox)return 1;
 NSString *session=NSUUID.UUID.UUIDString,*browser=browserParent();for(;;){uint32_t size=0;if(!transfer(STDIN_FILENO,&size,4,NO))break;if(!size||size>65536)break;NSMutableData *d=[NSMutableData dataWithLength:size];if(!transfer(STDIN_FILENO,d.mutableBytes,size,NO))break;id parsed=[NSJSONSerialization JSONObjectWithData:d options:0 error:nil];NSMutableDictionary *m=[parsed isKindOfClass:NSDictionary.class]?[parsed mutableCopy]:nil;NSDictionary *r;if(!m)r=@{@"ok":@NO,@"error":@"Invalid message"};else {m[@"session"]=session;if(browser)m[@"browser"]=browser;r=request(m);}NSMutableDictionary *reply=[r mutableCopy];if(m[@"id"])reply[@"id"]=m[@"id"];NSData *out=[NSJSONSerialization dataWithJSONObject:reply options:0 error:nil];size=(uint32_t)out.length;if(!transfer(STDOUT_FILENO,&size,4,YES)||!transfer(STDOUT_FILENO,(void *)out.bytes,size,YES))break;}
 if(browser)request(@{@"type":@"clear",@"browser":browser,@"session":session});
}return 0;}
