#import "BrowserBridge.h"
static void check(BOOL yes,const char *name){if(!yes){fprintf(stderr,"FAIL: %s\n",name);exit(1);}}
int main(){@autoreleasepool{
BrowserBridge *b=[BrowserBridge new];b.rules=[NSMutableDictionary new];NSDictionary *base=@{@"grayMode":@1,@"nightMode":@2,@"customWarmth":@YES,@"warmth":@30};
NSDictionary *domain=@{@"grayMode":@2,@"nightMode":@0,@"customWarmth":@NO,@"warmth":@0};NSDictionary *page=@{@"grayMode":@0,@"nightMode":@1,@"customWarmth":@YES,@"warmth":@77};
check([[b handle:@{@"type":@"set",@"site":@"EXAMPLE.COM",@"scope":@"domain",@"rule":domain}][@"ok"] boolValue],"domain save normalized");
check([[b handle:@{@"type":@"set",@"site":@"https://example.com/path?q=1#part",@"scope":@"url",@"rule":page}][@"ok"] boolValue],"exact URL save strips fragment");
[b handle:@{@"type":@"context",@"browser":@"com.brave.Browser",@"session":@"a",@"site":@"example.com",@"url":@"https://example.com/path?q=1#different",@"focused":@YES}];NSString *site=nil;NSDictionary *r=[b ruleForBrowser:@"com.brave.Browser" base:base site:&site];check([r[@"grayMode"] intValue]==2&&[r[@"nightMode"] intValue]==1&&[r[@"warmth"] intValue]==77,"URL/domain/browser per-effect precedence");check([site isEqual:@"https://example.com/path?q=1"],"website summary exact URL");
[b handle:@{@"type":@"context",@"browser":@"com.brave.Browser",@"session":@"a",@"site":@"example.com",@"url":@"https://example.com/path?q=2",@"focused":@YES}];r=[b ruleForBrowser:@"com.brave.Browser" base:base site:nil];check([r[@"grayMode"] intValue]==2&&[r[@"nightMode"] intValue]==2&&[r[@"warmth"] intValue]==30,"other query inherits domain/browser");
check([b ruleForBrowser:@"com.google.Chrome" base:base site:nil]==base,"browser contexts isolated");
[b handle:@{@"type":@"context",@"browser":@"com.google.Chrome",@"session":@"c",@"site":@"example.com",@"url":@"https://example.com/",@"focused":@YES}];check([[b ruleForBrowser:@"com.google.Chrome" base:base site:nil][@"grayMode"] intValue]==2,"rules shared across Chrome and Brave");
[b handle:@{@"type":@"clear",@"browser":@"com.brave.Browser",@"session":@"old"}];check(b.contexts[@"com.brave.Browser"]!=nil,"stale disconnect cannot clear newer context");
[b handle:@{@"type":@"clear",@"browser":@"com.brave.Browser",@"session":@"a"}];check([b ruleForBrowser:@"com.brave.Browser" base:base site:nil]==base,"disconnect restores browser fallback");
b.contexts[@"com.google.Chrome"]=@{@"site":@"example.com",@"url":@"",@"focused":@YES,@"time":[NSDate.date dateByAddingTimeInterval:-66],@"session":@"c"};check([b ruleForBrowser:@"com.google.Chrome" base:base site:nil]==base,"expired context fails safe");
for(id bad in @[@"not a dictionary",@{},@{@"type":@"set",@"site":@"example.com",@"rule":@{@"grayMode":@1,@"nightMode":@0,@"warmth":@[],@"customWarmth":@YES}},@{@"type":@"set",@"site":@"https://user:password@example.com/",@"scope":@"url",@"rule":page},@{@"type":@"set",@"site":@"example.com/path",@"scope":@"domain",@"rule":page},@{@"type":@"set",@"site":@"example.com",@"rule":@{@"grayMode":@3,@"nightMode":@0,@"warmth":@0,@"customWarmth":@NO}}])check(![[b handle:bad][@"ok"] boolValue],"malformed rule rejected");
b.contexts[@"com.brave.Browser"]=@{@"site":@"sub.example.com",@"url":@"https://sub.example.com/",@"focused":@YES,@"time":NSDate.date,@"session":@"a"};check([[b ruleForBrowser:@"com.brave.Browser" base:base site:nil][@"grayMode"] intValue]==2,"domain covers subdomains");b.contexts[@"com.brave.Browser"]=@{@"site":@"badexample.com",@"url":@"https://badexample.com/",@"focused":@YES,@"time":NSDate.date,@"session":@"a"};check([[b ruleForBrowser:@"com.brave.Browser" base:base site:nil][@"grayMode"] intValue]==1,"domain boundary does not match lookalike suffix");
[b handle:@{@"type":@"remove",@"scope":@"url",@"site":@"https://example.com/path?q=1"}];check(b.rules.count==1,"remove only selected scope");BrowserBridge *reloaded=[BrowserBridge new];check([reloaded.rules isEqual:b.rules],"native saved rules reload");
[b handle:@{@"type":@"context",@"browser":@"org.mozilla.firefox",@"session":@"f",@"site":@"example.com",@"url":@"https://example.com/",@"focused":@YES}];check([[b ruleForBrowser:@"org.mozilla.firefox" base:base site:nil][@"grayMode"] intValue]==2,"Firefox contexts are accepted and share the rules");[b handle:@{@"type":@"clear",@"browser":@"org.mozilla.firefox",@"session":@"f"}];check(![[b handle:@{@"type":@"context",@"browser":@"org.example.other",@"session":@"x",@"site":@"example.com",@"url":@"https://example.com/",@"focused":@YES}][@"ok"] boolValue],"unknown browsers are still rejected");
b.defaults=^NSDictionary *(NSString *browser){return [browser isEqual:@"com.brave.Browser"]?@{@"grayMode":@1,@"nightMode":@2,@"warmth":@30}:@{@"grayMode":@2,@"nightMode":@1,@"warmth":@0};};
NSDictionary *inherited=[b handle:@{@"type":@"get",@"scope":@"url",@"site":@"https://example.com/other",@"browser":@"com.brave.Browser"}][@"inherited"];check([inherited[@"grayMode"] intValue]==2&&[inherited[@"nightMode"] intValue]==2&&[inherited[@"warmth"] intValue]==30,"exact page inherits domain grayscale, browser night shift and warmth");
inherited=[b handle:@{@"type":@"get",@"scope":@"domain",@"site":@"example.com",@"browser":@"com.brave.Browser"}][@"inherited"];check([inherited[@"grayMode"] intValue]==1&&[inherited[@"warmth"] intValue]==30,"domain inherits the browser base, not its own rule");
[b handle:@{@"type":@"set",@"site":@"sub.example.com",@"scope":@"domain",@"rule":@{@"grayMode":@0,@"nightMode":@1,@"customWarmth":@YES,@"warmth":@55}}];inherited=[b handle:@{@"type":@"get",@"scope":@"url",@"site":@"https://deep.sub.example.com/x",@"browser":@"com.google.Chrome"}][@"inherited"];check([inherited[@"grayMode"] intValue]==2&&[inherited[@"nightMode"] intValue]==1&&[inherited[@"warmth"] intValue]==55,"longer domain wins per effect over shorter and browser base");
inherited=[b handle:@{@"type":@"get",@"scope":@"domain",@"site":@"unrelated.org",@"browser":@"com.google.Chrome"}][@"inherited"];check([inherited[@"grayMode"] intValue]==2&&[inherited[@"nightMode"] intValue]==1&&[inherited[@"warmth"] intValue]==0,"no matching domain falls back to the browser base");
b.defaults=nil;inherited=[b handle:@{@"type":@"get",@"scope":@"domain",@"site":@"unrelated.org"}][@"inherited"];check([inherited[@"grayMode"] intValue]==2&&[inherited[@"nightMode"] intValue]==2,"without an app base the reply still resolves to off");
[b handle:@{@"type":@"remove",@"scope":@"domain",@"site":@"sub.example.com"}];
puts("PASS: domain/URL normalization, exact query/fragment policy, per-effect inheritance, browser isolation/shared rules, disconnect/expiry, validation, removal, persistence and inherited-value resolution.");
}return 0;}
