#import "BrowserBridge.h"
#import <sys/socket.h>
#import <sys/un.h>
#import <sys/stat.h>
#import <unistd.h>
static BOOL bytes(int fd,void *p,size_t n,BOOL writing){while(n){ssize_t k=writing?write(fd,p,n):read(fd,p,n);if(k<=0)return NO;p+=k;n-=k;}return YES;}
static NSString *siteName(id value){if(![value isKindOfClass:NSString.class]||[value length]>253)return nil;NSString *s=[value lowercaseString];NSCharacterSet *allowed=[NSCharacterSet characterSetWithCharactersInString:@"abcdefghijklmnopqrstuvwxyz0123456789.-"];if(!s.length||[s rangeOfCharacterFromSet:allowed.invertedSet].location!=NSNotFound||[s hasPrefix:@"."]||[s hasSuffix:@"."]||[s containsString:@".."]||[s containsString:@"/"])return nil;return s;}
static NSString *pageURL(id value){if(![value isKindOfClass:NSString.class]||[value length]>8192)return nil;NSURLComponents *c=[NSURLComponents componentsWithString:value];if(![@[@"http",@"https"] containsObject:c.scheme.lowercaseString]||!siteName(c.host)||c.user||c.password)return nil;c.scheme=c.scheme.lowercaseString;c.host=c.host.lowercaseString;c.fragment=nil;if(!c.path.length)c.path=@"/";return c.string;}
@implementation BrowserBridge
+ (NSString *)socketPath {return [NSHomeDirectory() stringByAppendingPathComponent:@"Library/Application Support/Less Pull/browser.sock"];}
- (instancetype)init {if((self=[super init])){self.rules=[[NSUserDefaults.standardUserDefaults dictionaryForKey:@"websiteRules"] mutableCopy]?:[NSMutableDictionary new];self.contexts=[NSMutableDictionary new];self.listener=-1;}return self;}
- (NSDictionary *)handle:(NSDictionary *)m {
 if(![m isKindOfClass:NSDictionary.class])return @{@"ok":@NO,@"error":@"Invalid message"};NSString *type=m[@"type"],*site=[m[@"scope"] isEqual:@"url"]?pageURL(m[@"site"]):siteName(m[@"site"]);NSString *browser=m[@"browser"];
 if([type isEqual:@"context"]||[type isEqual:@"clear"]){if(![@[@"com.brave.Browser",@"com.google.Chrome",@"org.mozilla.firefox",@"com.operasoftware.Opera",@"com.microsoft.edgemac",@"com.apple.Safari"] containsObject:browser]||![m[@"session"] isKindOfClass:NSString.class])return @{@"ok":@NO,@"error":@"Unsupported browser"};if([type isEqual:@"clear"]){if([self.contexts[browser][@"session"] isEqual:m[@"session"]])[self.contexts removeObjectForKey:browser];}else self.contexts[browser]=@{@"site":siteName(m[@"site"])?:@"",@"url":pageURL(m[@"url"])?:@"",@"focused":@([m[@"focused"] boolValue]),@"time":NSDate.date,@"session":m[@"session"]};if(self.changed)self.changed();return @{@"ok":@YES};}
 if([type isEqual:@"list"])return @{@"ok":@YES,@"rules":self.rules};
 if(!site)return @{@"ok":@NO,@"error":@"Open an HTTP or HTTPS website first"};
 if([type isEqual:@"get"])return @{@"ok":@YES,@"rule":self.rules[site]?:NSNull.null,@"inherited":[self inheritedForSite:site browser:browser]};
 if([type isEqual:@"set"]){NSDictionary *r=m[@"rule"];if(![r isKindOfClass:NSDictionary.class])return @{@"ok":@NO,@"error":@"Invalid rule"};for(NSString *k in @[@"grayMode",@"nightMode"]){if(![r[k] isKindOfClass:NSNumber.class]||[r[k] doubleValue]!=[r[k] integerValue]||[r[k] integerValue]<0||[r[k] integerValue]>2)return @{@"ok":@NO,@"error":@"Invalid mode"};}if(![r[@"warmth"] isKindOfClass:NSNumber.class]||![r[@"customWarmth"] isKindOfClass:NSNumber.class])return @{@"ok":@NO,@"error":@"Invalid warmth"};double w=[r[@"warmth"] doubleValue];if(!isfinite(w)||w<0||w>100)return @{@"ok":@NO,@"error":@"Invalid warmth"};NSMutableDictionary *candidate=[self.rules mutableCopy];candidate[site]=r;if([NSJSONSerialization dataWithJSONObject:candidate options:0 error:nil].length>48000)return @{@"ok":@NO,@"error":@"Website rules are full. Remove an unused exception first."};self.rules[site]=@{@"grayMode":r[@"grayMode"],@"nightMode":r[@"nightMode"],@"customWarmth":@([r[@"customWarmth"] boolValue]),@"warmth":@(w)};}
 else if([type isEqual:@"remove"])[self.rules removeObjectForKey:site];else return @{@"ok":@NO,@"error":@"Unknown request"};
 [NSUserDefaults.standardUserDefaults setObject:self.rules forKey:@"websiteRules"];if(self.changed)self.changed();return @{@"ok":@YES};
}
- (NSDictionary *)ruleForBrowser:(NSString *)browser base:(NSDictionary *)base site:(NSString **)site {
 NSDictionary *c=self.contexts[browser];if(![c[@"focused"] boolValue]||[NSDate.date timeIntervalSinceDate:c[@"time"]?:NSDate.distantPast]>65)return base;
 NSMutableDictionary *result=[base mutableCopy]?:[NSMutableDictionary new];NSMutableArray *keys=[NSMutableArray new];NSString *host=c[@"site"]?:@"";for(NSString *key in self.rules){if(![key containsString:@"://"]&&([host isEqual:key]||[host hasSuffix:[@"." stringByAppendingString:key]]))[keys addObject:key];}[keys sortUsingComparator:^NSComparisonResult(NSString *a,NSString *b){return a.length<b.length?NSOrderedAscending:a.length>b.length?NSOrderedDescending:NSOrderedSame;}];[keys addObject:c[@"url"]?:@""];for(NSString *key in keys){NSDictionary *r=self.rules[key];BOOL overridden=NO;for(NSString *k in @[@"grayMode",@"nightMode"]){if([r[k] integerValue]){result[k]=r[k];overridden=YES;}}if([r[@"customWarmth"] boolValue]){result[@"customWarmth"]=@YES;result[@"warmth"]=r[@"warmth"];overridden=YES;}if(overridden&&site)*site=key;}return result;
}
// Resolves what a domain or exact page inherits: the browser-level base from the
// app (global settings plus the browser's app rule), then matching domain rules
// from shortest to longest, never the site's own rule. Values are never 0.
- (NSDictionary *)inheritedForSite:(NSString *)site browser:(NSString *)browser {
 NSDictionary *base=self.defaults?self.defaults(browser):nil;NSInteger gray=[base[@"grayMode"] integerValue]?:2,night=[base[@"nightMode"] integerValue]?:2;double warmth=[base[@"warmth"] doubleValue];
 NSString *host=[site containsString:@"://"]?[NSURLComponents componentsWithString:site].host:site;NSMutableArray *keys=[NSMutableArray new];
 for(NSString *key in self.rules)if(![key containsString:@"://"]&&![key isEqual:site]&&([host isEqual:key]||[host hasSuffix:[@"." stringByAppendingString:key]]))[keys addObject:key];
 [keys sortUsingComparator:^NSComparisonResult(NSString *a,NSString *b){return a.length<b.length?NSOrderedAscending:a.length>b.length?NSOrderedDescending:NSOrderedSame;}];
 for(NSString *key in keys){NSDictionary *r=self.rules[key];if([r[@"grayMode"] integerValue])gray=[r[@"grayMode"] integerValue];if([r[@"nightMode"] integerValue])night=[r[@"nightMode"] integerValue];if([r[@"customWarmth"] boolValue])warmth=[r[@"warmth"] doubleValue];}
 return @{@"grayMode":@(gray),@"nightMode":@(night),@"warmth":@(warmth)};
}
- (void)start {
 NSString *path=BrowserBridge.socketPath;[NSFileManager.defaultManager createDirectoryAtPath:path.stringByDeletingLastPathComponent withIntermediateDirectories:YES attributes:@{NSFilePosixPermissions:@0700} error:nil];struct sockaddr_un address={.sun_family=AF_UNIX};if([path lengthOfBytesUsingEncoding:NSUTF8StringEncoding]>=sizeof(address.sun_path))return;strlcpy(address.sun_path,path.fileSystemRepresentation,sizeof(address.sun_path));struct stat st;if(lstat(address.sun_path,&st)==0){if(st.st_uid!=getuid()||!S_ISSOCK(st.st_mode))return;unlink(address.sun_path);}int fd=socket(AF_UNIX,SOCK_STREAM,0);if(fd<0)return;if(bind(fd,(void *)&address,sizeof(address))||chmod(address.sun_path,0600)||listen(fd,8)){close(fd);return;}self.listener=fd;
 __weak BrowserBridge *weak=self;dispatch_async(dispatch_get_global_queue(QOS_CLASS_UTILITY,0),^{while(weak.listener==fd){int client=accept(fd,NULL,NULL);if(client<0)break;int noPipe=1;setsockopt(client,SOL_SOCKET,SO_NOSIGPIPE,&noPipe,sizeof(noPipe));struct timeval timeout={.tv_sec=3};setsockopt(client,SOL_SOCKET,SO_RCVTIMEO,&timeout,sizeof(timeout));setsockopt(client,SOL_SOCKET,SO_SNDTIMEO,&timeout,sizeof(timeout));uint32_t size=0;NSDictionary *reply=@{@"ok":@NO,@"error":@"Invalid request"};if(bytes(client,&size,4,NO)&&size>0&&size<=65536){NSMutableData *data=[NSMutableData dataWithLength:size];if(bytes(client,data.mutableBytes,size,NO)){id request=[NSJSONSerialization JSONObjectWithData:data options:0 error:nil];__block NSDictionary *response;dispatch_sync(dispatch_get_main_queue(),^{response=[weak handle:request];});reply=response?:reply;}}NSData *out=[NSJSONSerialization dataWithJSONObject:reply options:0 error:nil];uint32_t n=(uint32_t)out.length;bytes(client,&n,4,YES);bytes(client,(void *)out.bytes,n,YES);close(client);}});
}
- (void)stop {int fd=self.listener;self.listener=-1;if(fd>=0){shutdown(fd,SHUT_RDWR);close(fd);unlink(BrowserBridge.socketPath.fileSystemRepresentation);}}
@end
