import fs from 'node:fs';
import assert from 'node:assert/strict';
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn)}});
const messages=[];let tab={url:'https://example.com/path?q=1#part',active:true,windowId:1,incognito:false},focused=true,heartbeat;
globalThis.setInterval=fn=>{heartbeat=fn};
const nativePort={onMessage:event(),onDisconnect:event(),postMessage(m){messages.push(m);queueMicrotask(()=>nativePort.onMessage.listeners.forEach(fn=>fn({ok:true,id:m.id})))}};
globalThis.chrome={runtime:{id:'test',connectNative:()=>nativePort,onStartup:event(),onInstalled:event(),onMessage:event()},tabs:{query:async()=>[tab],onActivated:event(),onUpdated:event(),onRemoved:event()},windows:{get:async()=>({focused}),onFocusChanged:event()}};
globalThis.__lessPullTest={};const source=fs.readFileSync('Browser Extension/background.js','utf8');await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));const module=globalThis.__lessPullTest;
const settle=()=>new Promise(r=>setTimeout(r,10));await settle();
assert.deepEqual(module.identity(tab.url),{domain:'example.com',url:'https://example.com/path?q=1'});
assert.equal(messages.at(-1).focused,true);assert.equal(messages.at(-1).url,'https://example.com/path?q=1');
focused=false;await chrome.windows.onFocusChanged.listeners[0]();await settle();assert.equal(messages.at(-1).focused,true);
focused=true;tab={...tab,url:'https://other.example/p',incognito:true};await heartbeat();await settle();assert.equal(messages.at(-1).url,'');assert.equal(messages.at(-1).site,'');assert.equal(messages.at(-1).focused,false);
for(const url of ['chrome://settings','file:///tmp/x','https://user:pass@example.com/'])assert.equal(module.identity(url),null);
chrome.tabs.query=async()=>{throw new Error('Window unavailable')};await heartbeat();await settle();assert.equal(messages.at(-1).focused,false);assert.equal(messages.at(-1).url,'');
const before=messages.length;assert.equal(chrome.runtime.onMessage.listeners[0]({type:'set'},{id:'different'},()=>{}),false);assert.equal(messages.length,before);
const chromeManifest=JSON.parse(fs.readFileSync('Browser Extension/manifest.json','utf8')),firefoxManifest=JSON.parse(fs.readFileSync('Browser Extension/manifest.firefox.json','utf8'));
assert.equal(firefoxManifest.version,chromeManifest.version);assert.deepEqual(firefoxManifest.permissions,chromeManifest.permissions);assert.equal(firefoxManifest.action,undefined);assert.equal(chromeManifest.action,undefined);assert.deepEqual(firefoxManifest.background,{scripts:['background.js']});const safariManifest=JSON.parse(fs.readFileSync('Browser Extension/manifest.safari.json','utf8'));assert.deepEqual(safariManifest.background,{scripts:['background.js']});assert.equal(safariManifest.key,undefined);assert.equal(safariManifest.version,chromeManifest.version);assert.ok(!source.includes('export '),'background.js is a classic script');assert.equal(firefoxManifest.browser_specific_settings.gecko.id,'lesspull@jiriarion.com');assert.equal(firefoxManifest.key,undefined);assert.equal(chromeManifest.background.service_worker,'background.js');
// Safari path: no connectNative, sendNativeMessage with a callback.
const sent=[];globalThis.chrome={runtime:{id:'test',sendNativeMessage:(host,m,cb)=>{sent.push(m);cb({ok:true,id:m.id,rules:{}})},onStartup:event(),onInstalled:event(),onMessage:event()},tabs:{query:async()=>[{url:'https://example.com/',active:true,windowId:1,incognito:false}],onActivated:event(),onUpdated:event(),onRemoved:event()},windows:{get:async()=>({focused:true}),onFocusChanged:event()}};
globalThis.__lessPullTest={};await import('data:text/javascript;base64,'+Buffer.from(source+'\n//safari').toString('base64'));await settle();assert.equal(sent.at(-1).type,'context');assert.equal(sent.at(-1).site,'example.com');
await new Promise((resolve,reject)=>chrome.runtime.onMessage.listeners[0]({type:'list'},{id:'test'},r=>r.ok?resolve():reject(new Error(r.error))));assert.equal(sent.at(-1).type,'list');
console.log('PASS: active tab identity, exact URL/fragment handling, popup-safe active context, private-tab exclusion, unsupported pages, heartbeat, sender validation, resolved default labels (older app replies without them), a Firefox manifest that matches the Chrome one, no toolbar button or popup (the menu-bar menu is the interface), and the Safari sendNativeMessage path.');
