import fs from 'node:fs';
import assert from 'node:assert/strict';
const event=()=>({listeners:[],addListener(fn){this.listeners.push(fn)}});
const messages=[];let tab={url:'https://example.com/path?q=1#part',active:true,windowId:1,incognito:false},focused=true,heartbeat;
globalThis.setInterval=fn=>{heartbeat=fn};
const nativePort={onMessage:event(),onDisconnect:event(),postMessage(m){messages.push(m);queueMicrotask(()=>nativePort.onMessage.listeners.forEach(fn=>fn({ok:true,id:m.id})))}};
globalThis.chrome={runtime:{id:'test',connectNative:()=>nativePort,onStartup:event(),onInstalled:event(),onMessage:event()},tabs:{query:async()=>[tab],onActivated:event(),onUpdated:event(),onRemoved:event()},windows:{get:async()=>({focused}),onFocusChanged:event()}};
const source=fs.readFileSync('Browser Extension/background.js','utf8');const module=await import('data:text/javascript;base64,'+Buffer.from(source).toString('base64'));
const settle=()=>new Promise(r=>setTimeout(r,10));await settle();
assert.deepEqual(module.identity(tab.url),{domain:'example.com',url:'https://example.com/path?q=1'});
assert.equal(messages.at(-1).focused,true);assert.equal(messages.at(-1).url,'https://example.com/path?q=1');
focused=false;await chrome.windows.onFocusChanged.listeners[0]();await settle();assert.equal(messages.at(-1).focused,true);
focused=true;tab={...tab,url:'https://other.example/p',incognito:true};await heartbeat();await settle();assert.equal(messages.at(-1).url,'');assert.equal(messages.at(-1).site,'');assert.equal(messages.at(-1).focused,false);
for(const url of ['chrome://settings','file:///tmp/x','https://user:pass@example.com/'])assert.equal(module.identity(url),null);
chrome.tabs.query=async()=>{throw new Error('Window unavailable')};await heartbeat();await settle();assert.equal(messages.at(-1).focused,false);assert.equal(messages.at(-1).url,'');
const before=messages.length;assert.equal(chrome.runtime.onMessage.listeners[0]({type:'set'},{id:'different'},()=>{}),false);assert.equal(messages.length,before);
const chromeManifest=JSON.parse(fs.readFileSync('Browser Extension/manifest.json','utf8')),firefoxManifest=JSON.parse(fs.readFileSync('Browser Extension/manifest.firefox.json','utf8'));
assert.equal(firefoxManifest.version,chromeManifest.version);assert.deepEqual(firefoxManifest.permissions,chromeManifest.permissions);assert.deepEqual(firefoxManifest.action,chromeManifest.action);assert.deepEqual(firefoxManifest.background,{scripts:['background.js'],type:'module'});assert.equal(firefoxManifest.browser_specific_settings.gecko.id,'lesspull@jiriarion.com');assert.equal(firefoxManifest.key,undefined);assert.equal(chromeManifest.background.service_worker,'background.js');
const warmth=await import('./Browser Extension/warmth.js');
assert.deepEqual(warmth.warmthGains(0),[1,1,1]);assert.ok(warmth.warmthGains(3)[1]<0.01&&warmth.warmthGains(3)[2]<0.001);assert.ok(warmth.warmthGains(1.5)[1]>warmth.warmthGains(2)[1]);assert.ok(warmth.rampGradient(4).startsWith('linear-gradient(to right, rgb(255,255,255) 0.0%')&&warmth.rampGradient(4).includes('100.0%'));
const popup=fs.readFileSync('Browser Extension/popup.html','utf8');for(const id of ['status','site','scope','current','gray','night','gray-default','night-default','inherit','inherit-label','warmth','percent','reset','save','remove','saved','form'])assert.ok(popup.includes(`id="${id}"`),`popup has #${id}`);
const labels=await import('./Browser Extension/labels.js');
assert.equal(labels.defaultLabel({grayMode:1,nightMode:2},'grayMode'),'Use default (On)');assert.equal(labels.defaultLabel({grayMode:1,nightMode:2},'nightMode'),'Use default (Off)');assert.equal(labels.defaultLabel(undefined,'grayMode'),'Use default');assert.equal(labels.defaultLabel({grayMode:0},'grayMode'),'Use default');
assert.equal(labels.warmthLabel({warmth:35}),'Use default warmth (35%)');assert.equal(labels.warmthLabel({warmth:0}),'Use default warmth (Off)');assert.equal(labels.warmthLabel({}),'Use default warmth');assert.equal(labels.warmthLabel(undefined),'Use default warmth');
console.log('PASS: active tab identity, exact URL/fragment handling, popup-safe active context, private-tab exclusion, unsupported pages, heartbeat, sender validation, resolved default labels (older app replies without them), a Firefox manifest that matches the Chrome one, the warmth ramp port, and the popup’s controls.');
